// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdR1_vSTsyfZHlhZ9TgPX2WZDuRzIkMOk',
    appId: '1:861794811820:web:ac387d2a1d56d46bc64409',
    messagingSenderId: '861794811820',
    projectId: 'voice-expense-smart',
    authDomain: 'voice-expense-smart.firebaseapp.com',
    storageBucket: 'voice-expense-smart.firebasestorage.app',
    measurementId: 'G-9MZ21KCXBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYOgBwTw2KdY6hs6X1JnlzBaj55y4t0WA',
    appId: '1:861794811820:android:2495beda42cfaadcc64409',
    messagingSenderId: '861794811820',
    projectId: 'voice-expense-smart',
    storageBucket: 'voice-expense-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD0d2MSEvmsEp62SDYMVgddS6N4NN6KFc',
    appId: '1:861794811820:ios:7537654421d98dfdc64409',
    messagingSenderId: '861794811820',
    projectId: 'voice-expense-smart',
    storageBucket: 'voice-expense-smart.firebasestorage.app',
    iosBundleId: 'com.example.voiceExpenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD0d2MSEvmsEp62SDYMVgddS6N4NN6KFc',
    appId: '1:861794811820:ios:7537654421d98dfdc64409',
    messagingSenderId: '861794811820',
    projectId: 'voice-expense-smart',
    storageBucket: 'voice-expense-smart.firebasestorage.app',
    iosBundleId: 'com.example.voiceExpenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdR1_vSTsyfZHlhZ9TgPX2WZDuRzIkMOk',
    appId: '1:861794811820:web:c7abf299de66af7dc64409',
    messagingSenderId: '861794811820',
    projectId: 'voice-expense-smart',
    authDomain: 'voice-expense-smart.firebaseapp.com',
    storageBucket: 'voice-expense-smart.firebasestorage.app',
    measurementId: 'G-0ZMPNGR9NF',
  );
}
